### ISSUE TITLE
GITHUB_AUTH_TOKEN未设置的提示不合理

### ISSUE THREAD

**Issue by Yikun** [Yikun/reposcore#2]
在最开始直接拦住吧，如果不设置的话，就直接break退出吧，没必要再执行后续的流程了。

```
(venv) ➜  score_projects git:(main) ✗ score_projects --projects_list ./score_projects/projects.txt --result_file result.csv
Exception occurred when reading repo: https://github.com/moosefs/moosefs
GITHUB_AUTH_TOKEN needs to be set.
Exception occurred when reading repo: https://github.com/moosefs/moosefs
GITHUB_AUTH_TOKEN needs to be set.
Exception occurred when reading repo: https://github.com/moosefs/moosefs
GITHUB_AUTH_TOKEN needs to be set.
Exception occurred when reading repo: https://github.com/lizardfs/lizardfs
GITHUB_AUTH_TOKEN needs to be set.
Exception occurred when reading repo: https://github.com/lizardfs/lizardfs
GITHUB_AUTH_TOKEN needs to be set.
Exception occurred when reading repo: https://github.com/lizardfs/lizardfs
GITHUB_AUTH_TOKEN needs to be set.
Traceback (most recent call last):
  File "/Users/jiangyikun/huawei/score_projects/venv/bin/score_projects", line 11, in <module>
    load_entry_point('score-projects==1.0.8', 'console_scripts', 'score_projects')()
  File "/Users/jiangyikun/huawei/score_projects/venv/lib/python3.7/site-packages/score_projects-1.0.8-py3.7.egg/score_projects/score_projects.py", line 79, in main
    csv_writer.writerow(header)
_csv.Error: iterable expected, not NoneType
```

**Comment by wangxiyuan** [comment]
It's fixed already
