### ISSUE TITLE
Failed to calculate the openstack project score

### ISSUE THREAD

**Issue by Yikun** [Yikun/reposcore#36]
```
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/repos/reposcore/reposcore/stat/stat.py", line 45, in _worker
    return_dict[param] = getattr(repo, param)
  File "/opt/repos/reposcore/reposcore/repo/repo.py", line 102, in core_effort
    add = self._core_line_change_recent_year()[0]
  File "/opt/repos/reposcore/reposcore/repo/repo.py", line 113, in _core_line_change_recent_year
    change[match] = self._code_line_change_recent_year('*.' + match)
  File "/opt/repos/reposcore/reposcore/repo/repo.py", line 86, in _code_line_change_recent_year
    _count_code_line(self.local_repo, self.local_name)
  File "/opt/repos/reposcore/reposcore/repo/repo.py", line 74, in _count_code_line
    for module in repo.submodules:
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/repo/base.py", line 337, in submodules
    return Submodule.list_items(self)
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/util.py", line 930, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/objects/submodule/base.py", line 1184, in iter_items
    rt = pc.tree                                # root tree
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/gitdb/util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/objects/commit.py", line 142, in _set_cache_
    _binsha, _typename, self.size, stream = self.repo.odb.stream(self.binsha)
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/db.py", line 42, in stream
    hexsha, typename, size, stream = self._git.stream_object_data(bin_to_hex(sha))
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/cmd.py", line 1086, in stream_object_data
    hexsha, typename, size = self.__get_object_header(cmd, ref)
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/cmd.py", line 1058, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/cmd.py", line 1022, in _parse_object_header
    raise ValueError("SHA %s could not be resolved, git returned: %r" % (tokens[0], header_line.strip()))
ValueError: SHA b'\xdd4=\x06' could not be resolved, git returned: b'\xdd4=\x06 .f\x80\xdeuV\xabJ\xba\x9d\x16\x8f160000 adjutant-ui\x00\xbb\x92\x84\x1b[\xee_|\x01U\xc4\x85yY\xf2\x1e\xed\x9d\xdf\xb9160000 ansible-config_template\x00\xa64|8\x11T\xde\xab3\xac\xa4\x91\x88\xbe\xa1\x99-\xc1y\xce160000 ansible-hardening\x00ND\xa5K\x95\xb7o\xec8\r\x1b\xbd\xf8*\x93\x9b\x02Z\x12\x8d160000 ansible-role-atos-hsm\x00\xc5\xe5\xb2B{\xdb\xf5\x9b\xb4\xbf\xd8u\xf4\xc2mn\x12"GG160000 ansible-role-chrony\x00\xb2^\x82\xc0\xe3\x142ow\r6\x8e\xf4.*2\xa6h\x08\xb3160000 ansible-role-collect-logs\x00P?\xa8%\x0fjn\x80D\xa2\x0f\x03\x12\x1d\xeb\x90\xb4\x97\x1dP160000 ansible-role-container-registry\x00\xa0\xa3\x14\xad\xe3_R!R\x16\xdb\xea\xea\x97\xe2\xd7zy\x92\xe4160000 ansible-role-lunasa-hsm\x00\xb3\x98\x1co\x8b\x01:\xff\xa4\x84\xfa\xc1\'\x0e\xf5{\x8b)"a160000 ansible-role-openstack-operations\x0097\xeaN~L\xea\x06\x0f\x98\x03L\xe6^ \xca\xbf\x86\x9d\xc8160000 ansible-role-python_venv_build\x00\xb4c\xc7e\xeb\x94\xcd7\xae?\xbd \xae\xfcV\x1c\xcf\x92\x18\xa2160000 ansible-role-qdrouterd\x00\xdfB`\xf6\x12\x19\xb4=\xac\xf1\x0c\xa2\xb2\xd5)\xa1\xc8~F0160000 ansible-role-redhat-subscription\x00\xca\x1f\xcc\xee\xb3n\xfamfo,y\xa2\xa5\xa4\x99\xe8H{\xaf160000 ansible-role-systemd_mount\x00H;\x10\xe5\xe9\x89i/5\x8b\xbaI\xf4\x17\xbe\x0f\xbbn\x00\xd8160000 ansible-role-systemd_networkd\x00H\xa2\x17\xbf-\x8f\x14\x16T\x1c\x92\xb4L\xbc\x80Q\x80\x13\xf3"160000 ansible-role-systemd_service\x00<\x92M%1\xe4qD\x82\x83]\xcdr \x95V\xf3\xd1\xb59160000 ansible-role-thales-hsm\x00\xa7\x87\xe6X\xda\xa9v(F\xc1x>w\xdajd\xb4\x841\x19160000 ansible-role-tripleo-modify-image\x00\x99a\xcf\x84\xa3g\xb2\x12R\xdd\x7f\x8c\t6\xd7M\x9a\x19\x87B160000 ansible-role-uwsgi\x00P\xa9A\xf5R\x94\xbeL\x7f\xff\xc7\x7fk\xcf\x99\xd9\xffb\xa1\xd5160000 aodh\x00\xa5\x84\x05l\x0e\xa0\rM\x90\xb0^$\xf9\x9cTP<q\x0b*160000 automaton\x00\x89\xb6}\xdb\x9c3\xe7:\x97fy\xfc!\x02\xe2\x99\xd0\x16Z\xe0160000 barbican\x00\x85%{Vs\xbb\xddS\xe4\x13\xca\xac\x05:\xf6\x1dxCg)160000 barbican-specs\x00\xd0br?\x97\xc2V(\xde\xff\x92\x1b\xe9V\xe3!\xbc\xa2\xccW160000 barbican-tempest-plugin\x00S\xdc\xabp\xf2o\x8e\x99\x0f\xceB^\xe1\x00^\xf3\xf7u\xd1t160000 barbican-ui\x00:x\xa7CBcv%\x0fCP\x8dB\x81\xe8lu\x06rq160000 bashate\x008\x9f\x89\x17\xcd\xfc\x8bS\xfd?f\xc2wW\xc1\x19\xde|-\x8c160000 bifrost\x00\x7f\x0e\xffWkI\x99\xe8'
```

```
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/repos/reposcore/reposcore/stat/stat.py", line 45, in _worker
    return_dict[param] = getattr(repo, param)
  File "/opt/repos/reposcore/reposcore/repo/repo.py", line 92, in code_effort
    add = self._code_line_change_recent_year()[0]
  File "/opt/repos/reposcore/reposcore/repo/repo.py", line 86, in _code_line_change_recent_year
    _count_code_line(self.local_repo, self.local_name)
  File "/opt/repos/reposcore/reposcore/repo/repo.py", line 74, in _count_code_line
    for module in repo.submodules:
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/repo/base.py", line 337, in submodules
    return Submodule.list_items(self)
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/util.py", line 930, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/objects/submodule/base.py", line 1198, in iter_items
    sm = rt[p]
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/objects/tree.py", line 294, in __getitem__
    return self.join(item)
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/objects/tree.py", line 235, in join
    for info in self._cache:
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/gitdb/util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/objects/tree.py", line 193, in _set_cache_
    ostream = self.repo.odb.stream(self.binsha)
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/db.py", line 42, in stream
    hexsha, typename, size, stream = self._git.stream_object_data(bin_to_hex(sha))
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/cmd.py", line 1086, in stream_object_data
    hexsha, typename, size = self.__get_object_header(cmd, ref)
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/cmd.py", line 1058, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/cmd.py", line 1022, in _parse_object_header
    raise ValueError("SHA %s could not be resolved, git returned: %r" % (tokens[0], header_line.strip()))
ValueError: SHA b'100644' could not be resolved, git returned: b'100644 .gitmodules\x00\x96\xb2OJ\xf0l+~M\x80H\\\x84B{$\xccw\xf5\x00100644 .gitreview\x00s\xafT\xd47\x95\xb1\x8e\xc2\xd74\t\x85\xb3\xb3\xc9\xe2\xfe\xf1\x8c100644 LICENSE\x00h\xc7q\xa0\x99\x95\x82\x11\x16\x93w\xd7f\xa78\x94"\xf5W=100644 README.rst\x001\x89\x86\xcd\x1c\xa7\t\xa3Z}\xf7\x1c8a\xac\xdc4\x80s\xa2160000 adjutant\x00\x84\''
```

**Comment by Yikun** [comment]
```
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/repos/reposcore/reposcore/stat/stat.py", line 45, in _worker
    return_dict[param] = getattr(repo, param)
  File "/opt/repos/reposcore/reposcore/repo/repo.py", line 107, in core_line_change_recent_year
    add, dele, detail = self._core_line_change_recent_year()
  File "/opt/repos/reposcore/reposcore/repo/repo.py", line 113, in _core_line_change_recent_year
    change[match] = self._code_line_change_recent_year('*.' + match)
  File "/opt/repos/reposcore/reposcore/repo/repo.py", line 86, in _code_line_change_recent_year
    _count_code_line(self.local_repo, self.local_name)
  File "/opt/repos/reposcore/reposcore/repo/repo.py", line 74, in _count_code_line
    for module in repo.submodules:
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/repo/base.py", line 337, in submodules
    return Submodule.list_items(self)
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/util.py", line 930, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/objects/submodule/base.py", line 1184, in iter_items
    rt = pc.tree                                # root tree
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/gitdb/util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/objects/commit.py", line 143, in _set_cache_
    self._deserialize(BytesIO(stream.read()))
  File "/opt/repos/reposcore/venv/lib/python3.6/site-packages/git/cmd.py", line 446, in read
    data = self._stream.read(size)
ValueError: read of closed file
```

**Comment by wangxiyuan** [comment]
https://github.com/kunpengcompute/reposcore/pull/34
