### ISSUE TITLE
failed to load author

### ISSUE THREAD

**Issue by Yikun** [Yikun/reposcore#37]
```
Exception in thread Thread-60:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/reposcore/reposcore/stat/stat.py", line 45, in _worker
    return_dict[param] = getattr(repo, param)
  File "/root/reposcore/reposcore/repo/repo.py", line 154, in activity_contributor_count_recent_year
    author = json.loads(author_raw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by wangxiyuan** [comment]
https://github.com/kunpengcompute/reposcore/pull/38 用这个patch跑一下，会raise出错的author，然后在name_fix里加一下

**Comment by Yikun** [comment]
```
(venv) root@yikun-arm:~/reposcore# reposcore -c etc/reposcore.conf --project-list ~/reposcore/test/ci-test.txt --result-file xxx.csv
> /root/reposcore/reposcore/repo/repo.py(159)activity_contributor_count_recent_year()
-> raise Exception('can not parse json raw %s' % author_raw)
(Pdb) l
154                 try:
155                     author = json.loads(author_raw)
156                 except Exception:
157                     if not author_raw:
158                         import pdb;pdb.set_trace()
159  ->                 raise Exception('can not parse json raw %s' % author_raw)
160                 if not author_list.get(author['name']):
161                     author_list[author['name']] = {
162                         "email": author['email'],
163                         "commit_count": 1
164                     }
(Pdb) p author_raw
''
```

@wangxiyuan author是空的没处理

**Comment by Yikun** [comment]
```
(Pdb) self.local_repo.git.log('--since', self.since_time, out_format).replace('\\', '').split('\n')
['']
(Pdb) self.local_repo
<git.repo.base.Repo '/opt/repos/kite-sdk/kite/.git'>
```

https://github.com/kite-sdk/kite
如果一个仓库，没有贡献，返回的不是空列表，返回的是个`['']`
