### ISSUE TITLE
openstack updata failed

### ISSUE THREAD

**Issue by Yikun** [Yikun/reposcore#42]
```
Start updating openstack/openstack
Traceback (most recent call last):
  File "/root/reposcore/venv/bin/reposcore", line 10, in <module>
    sys.exit(main())
  File "/root/reposcore/reposcore/cli.py", line 143, in main
    rs.run()
  File "/root/reposcore/reposcore/cli.py", line 109, in run
    self._auto_update_repo(repo_urls)
  File "/root/reposcore/reposcore/cli.py", line 97, in _auto_update_repo
    local_repo.git.submodule(*args)
  File "/root/reposcore/venv/lib/python3.6/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/root/reposcore/venv/lib/python3.6/site-packages/git/cmd.py", line 1006, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/root/reposcore/venv/lib/python3.6/site-packages/git/cmd.py", line 823, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git submodule update -c submodule."openstack-tempest-skiplist".update=none -c submodule."whitebox-tempest-plugin".update=none -c submodule."xstatic-graphlib".update=none
  stderr: 'usage: git submodule [--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] deinit [-f|--force] (--all| [--] <path>...)
   or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--checkout|--merge|--rebase] [--[no-]recommend-shallow] [--reference <repository>] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--recursive] [--] [<path>...]
   or: git submodule [--quiet] absorbgitdirs [--] [<path>...]'
```

**Comment by Yikun** [comment]
-c需要放到submodule update前面

git -c xxxx  submodule update
